name: Deploy JamComments API to Azure Functions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of environment to deploy (staging, prod)'
        required: true
        default: 'staging'
      fullDeployment:
        description: 'Whether to do a full deployment or not'
        required: true
        default: 'false'
  push:
    branches:
      - dev
      - master

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)
  fullDeployment: ${{ github.event.inputs.fullDeployment || 'false' }}

defaults:
  run:
    shell: bash

jobs:
  setupEnv:
    name: Set up environments
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - name: setup environment variables
        id: setupEnv
        run: |
          echo "Setup environment and secrets"
          if [ "${{ github.event.inputs.environment }}" = "staging" ] || [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "::set-output name=environment::staging"
            echo "::set-output name=githubEnvironment::Development"
          elif [ "${{ github.event.inputs.environment }}" = "prod" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "::set-output name=environment::prod"
            echo "::set-output name=githubEnvironment::Production"
          fi
    outputs:
      environment: ${{ steps.setupEnv.outputs.environment }}
      githubEnvironment: ${{ steps.setupEnv.outputs.githubEnvironment }}
      name: jamcomments-${{ steps.setupEnv.outputs.environment }}-eus-fapp

  build-and-deploy:
    environment: ${{ needs.setupEnv.outputs.githubEnvironment }}
    concurrency: ${{ needs.setupEnv.outputs.name }}
    needs:
      - setupEnv
    env:
      environment: ${{ needs.setupEnv.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: 'Resolve Project Dependencies Using yarn'
      shell: bash
      run: |
        yarn
        yarn build
        yarn test

    - name: Azure Login
      timeout-minutes: 5
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create infrastructure
      run:  infra/azure/scripts/create-funcapp.sh
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: 'Deploy to Azure Functions'
      uses: montudor/action-zip@v1
      run: |
        zip -r functionapp.zip . -x@.funcignore -x .funcignore
        az functionapp deployment source config-zip -g jamcomments-${{ steps.setupEnv.outputs.environment }}-eus-rgp -n jamcomments-${{ steps.setupEnv.outputs.environment }}-eus-fapp --src functionapp.zip

    - name: Azure Logout
      if: ${{ always() }}
      run: |
        az logout
        az cache purge
        az account clear

